site_name: My Docs
theme: 
  name: 'material'


nav:
- Home: index.md
- Bioinformatics Learning:
    - Git: Gitlearning.md
    - Linux: Linuxlearning.md
    - Vim: Vimlearning.md
- About: about.md
- 小傻瓜如何学习使用电脑: shagua.md
